function sha256Hex(str){const enc=new TextEncoder().encode(str);if(!(window.crypto&&window.crypto.subtle)){// Fallback: FNV-1a 32-bit (not cryptographic, used only if SubtleCrypto unavailable)
  let h=0x811c9dc5;for(let i=0;i<enc.length;i++){h^=enc[i];h+= (h<<1) + (h<<4) + (h<<7) + (h<<8) + (h<<24)}h=h>>>0;return Promise.resolve(h.toString(16).padStart(8,'0'))}
return crypto.subtle.digest('SHA-256',enc).then(buf=>{const v=new Uint8Array(buf);let s='';for(let b of v){s+=b.toString(16).padStart(2,'0')}return s})}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('ImageAdminDB',1);req.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains('users')){db.createObjectStore('users',{keyPath:'username'})}if(!db.objectStoreNames.contains('images')){const s=db.createObjectStore('images',{keyPath:'compoundId'});s.createIndex('page','page',{unique:false});s.createIndex('imageId','imageId',{unique:false});s.createIndex('updatedAt','updatedAt',{unique:false})}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function getUser(){return openDB().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction('users','readonly');const st=tx.objectStore('users');const r=st.get('admin');r.onsuccess=()=>{resolve(r.result||null)};r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close()}))}
function setUser(hash){return openDB().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction('users','readwrite');const st=tx.objectStore('users');st.put({username:'admin',passwordHash:hash,createdAt:new Date().toISOString()});tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}}))}
function verifyUser(hash){return getUser().then(u=>!!u&&u.passwordHash===hash)}
function addImage(item){return openDB().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction('images','readwrite');const st=tx.objectStore('images');st.put(item);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}}))}
function listImages(){return openDB().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction('images','readonly');const st=tx.objectStore('images');const r=st.getAll();r.onsuccess=()=>{resolve(r.result||[])};r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close()}))}
function deleteImage(compoundId){return openDB().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction('images','readwrite');const st=tx.objectStore('images');st.delete(compoundId);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}}))}
function updateImage(partial){return openDB().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction('images','readwrite');const st=tx.objectStore('images');const r=st.get(partial.compoundId);r.onsuccess=()=>{let it=r.result;if(!it){const newItem={compoundId:partial.compoundId,page:partial.page||'',imageId:partial.imageId,imageIndex:partial.imageIndex,originalSrc:partial.originalSrc||'',alt:partial.alt||'',title:partial.title||'',replacementDataUrl:partial.replacementDataUrl||null,updatedAt:partial.updatedAt||new Date().toISOString()};st.put(newItem)}else{Object.assign(it,partial);if(!partial.updatedAt){it.updatedAt=new Date().toISOString()}st.put(it)}};r.onerror=()=>reject(r.error);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}}))}
function readFileDataURL(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=()=>reject(fr.error);fr.readAsDataURL(file)})}
function renderRows(items){const tbody=document.getElementById('imagesTbody');const pageFilter=document.getElementById('pageFilter');const term=(document.getElementById('searchInput').value||'').toLowerCase();tbody.innerHTML='';const pages=new Set();items.forEach(i=>pages.add(i.page));const existing=[...pageFilter.options].map(o=>o.value);pages.forEach(p=>{if(!existing.includes(p)){const opt=document.createElement('option');opt.value=p;opt.textContent=p;pageFilter.appendChild(opt)}});let filtered=items.slice();const pf=pageFilter.value;if(pf!=='all'){filtered=filtered.filter(i=>i.page===pf)}if(term){filtered=filtered.filter(i=>(i.page||'').toLowerCase().includes(term)||(i.imageId||'').toLowerCase().includes(term)||(i.alt||'').toLowerCase().includes(term))}filtered.sort((a,b)=>new Date(b.updatedAt||0)-new Date(a.updatedAt||0));if(filtered.length===0){const tr=document.createElement('tr');tr.innerHTML='<td colspan="11" class="no-data">No images found.</td>';tbody.appendChild(tr);return}filtered.forEach(i=>{const tr=document.createElement('tr');const dt=i.updatedAt?new Date(i.updatedAt).toLocaleString('en-IN'):'';tr.innerHTML=`
<td><input type="checkbox" class="rowSel" data-id="${i.compoundId}"></td>
<td>${i.replacementDataUrl?`<img class="thumb" src="${i.replacementDataUrl}">`:`<img class="thumb" src="${i.originalSrc||''}">`}</td>
<td>${i.page}</td>
<td>${i.imageId}</td>
<td><input class="input altInput" data-id="${i.compoundId}" value="${i.alt||''}"></td>
<td><input class="input titleInput" data-id="${i.compoundId}" value="${i.title||''}"></td>
<td>${i.originalSrc||''}</td>
<td>${dt}</td>
<td><input type="file" class="fileInput" data-id="${i.compoundId}" accept="image/*"></td>
<td><button class="btn primary saveBtn" data-id="${i.compoundId}">Save</button></td>
<td><button class="btn danger delBtn" data-id="${i.compoundId}">Delete</button></td>
`;tbody.appendChild(tr)});document.querySelectorAll('.saveBtn').forEach(b=>{b.addEventListener('click',async e=>{const id=e.target.dataset.id;const alt=document.querySelector(`.altInput[data-id="${id}"]`).value;const title=document.querySelector(`.titleInput[data-id="${id}"]`).value;const fileInp=document.querySelector(`.fileInput[data-id="${id}"]`);let dataUrl=null;if(fileInp&&fileInp.files&&fileInp.files[0]){dataUrl=await readFileDataURL(fileInp.files[0])}await updateImage({compoundId:id,alt:alt,title:title,replacementDataUrl:dataUrl,updatedAt:new Date().toISOString()});const items=await listImages();renderRows(items)})});document.querySelectorAll('.delBtn').forEach(b=>{b.addEventListener('click',async e=>{const id=e.target.dataset.id;if(confirm('Delete this mapping?')){await deleteImage(id);e.target.closest('tr').remove()}})});document.getElementById('selectAll').addEventListener('change',e=>{document.querySelectorAll('.rowSel').forEach(cb=>cb.checked=e.target.checked)})}
function compoundId(page,imageId){return `${page}||${imageId}`}
function init(){const logout=document.getElementById('logoutBtn');logout.addEventListener('click',()=>{sessionStorage.removeItem('imagesAdminLoggedIn');location.reload()});
  getUser().then(u=>{const auth=document.getElementById('authSection');const panel=document.getElementById('panelSection');const setup=document.getElementById('setupForm');const login=document.getElementById('loginForm');const title=document.getElementById('authTitle');try{
    if(!u){title.textContent='Set Admin Password';setup.style.display='grid';login.style.display='none';setup.addEventListener('submit',async e=>{e.preventDefault();const pw=document.getElementById('setupPassword').value;if(!pw){alert('Enter password');return}const hash=await sha256Hex(pw);await setUser(hash);sessionStorage.setItem('imagesAdminLoggedIn','true');auth.style.display='none';panel.style.display='block';loadPanel()})}
    else {title.textContent='Admin Login';login.style.display='grid';setup.style.display='none';login.addEventListener('submit',async e=>{e.preventDefault();const pw=document.getElementById('loginPassword').value;const hash=await sha256Hex(pw);const ok=await verifyUser(hash);if(ok){sessionStorage.setItem('imagesAdminLoggedIn','true');auth.style.display='none';panel.style.display='block';loadPanel()}else{alert('Invalid password')}})}
    const logged=sessionStorage.getItem('imagesAdminLoggedIn')==='true';if(logged){auth.style.display='none';panel.style.display='block';loadPanel()}
  } catch(err){login.style.display='grid';setup.style.display='none'}
  }).catch(()=>{const auth=document.getElementById('authSection');const panel=document.getElementById('panelSection');const setup=document.getElementById('setupForm');const login=document.getElementById('loginForm');auth.style.display='block';login.style.display='grid';setup.style.display='none';panel.style.display='none';});
}
document.addEventListener('DOMContentLoaded',()=>{setupSimple()})
function loadPanel(){const search=document.getElementById('searchInput');const pageFilter=document.getElementById('pageFilter');const refresh=document.getElementById('refreshBtn');search.addEventListener('input',async()=>{renderRows(await listImages())});pageFilter.addEventListener('change',async()=>{renderRows(await listImages())});refresh.addEventListener('click',async()=>{renderRows(await listImages())});listImages().then(renderRows)}
const AVAILABLE_PAGES=["nitin.html","admin-dashboard.html","marriage.html","normal.html","cultural.html","baby-shower.html","festival.html","bridal.html","booking.html","gallery.html","thank-you.html","admin.html","services.html","contact.html","about.html"];
function setupSimple(){const pageSel=document.getElementById('simplePageSelect');const idxSel=document.getElementById('simpleImageIndex');const fileInp=document.getElementById('simpleFile');const form=document.getElementById('simpleForm');AVAILABLE_PAGES.forEach(p=>{const opt=document.createElement('option');opt.value=p;opt.textContent=p;pageSel.appendChild(opt)});pageSel.addEventListener('change',()=>{const p=pageSel.value;if(!p){idxSel.innerHTML='<option value="">Select a page first</option>';return}const frame=document.getElementById('pagePreviewFrame');frame.src=p;frame.onload=()=>{try{const doc=frame.contentDocument;const imgs=[...doc.querySelectorAll('img')];idxSel.innerHTML='';if(imgs.length===0){idxSel.innerHTML='<option value="">No images on page</option>';return}for(let i=0;i<imgs.length;i++){const opt=document.createElement('option');opt.value=String(i+1);const al=imgs[i].getAttribute('alt')||'';const src=imgs[i].getAttribute('src')||'';opt.textContent=`${i+1} — ${al || src}`;idxSel.appendChild(opt)}}catch(e){idxSel.innerHTML='';for(let i=1;i<=20;i++){const opt=document.createElement('option');opt.value=String(i);opt.textContent=`${i}`;idxSel.appendChild(opt)}}}});form.addEventListener('submit',async e=>{e.preventDefault();const p=pageSel.value;const idx=idxSel.value;const f=fileInp.files[0];if(!p||!idx||!f){alert('Select page, image index and upload image');return}const dataUrl=await readFileDataURL(f);const compoundId=`${p}||#${idx}`;await updateImage({compoundId, page:p, imageIndex:Number(idx), replacementDataUrl:dataUrl, updatedAt:new Date().toISOString()});alert('Saved. Open the page to see the replacement.')});}
document.addEventListener('DOMContentLoaded',init)
